-- Customer payments (khata settlements) — one row per payment a customer makes
-- against their credit balance. Powers the per-customer Statement (passbook) on
-- the Accounts page: debits come from credit bills, credits come from these rows.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New query
-- -> paste -> Run). Safe to re-run — idempotent.

create table if not exists public.customer_payments (
    id           bigint generated by default as identity primary key,
    payment_id   text not null,
    user_id      text not null,
    name         text not null default '',
    amount       numeric not null default 0,
    pay_date     date,
    note         text default '',
    saved_at     timestamptz default now()
);

create unique index if not exists customer_payments_pid_uniq
    on public.customer_payments (payment_id);

grant select, insert, update, delete on public.customer_payments to anon, authenticated;

alter table public.customer_payments enable row level security;

drop policy if exists tenant_rw on public.customer_payments;
create policy tenant_rw on public.customer_payments
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());
