-- Audit log: who did what, when. One row per logged action (sale, purchase,
-- delete, edit, return, payment…). Viewed on the Report page.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New query
-- -> paste -> Run). Safe to re-run — everything is IF NOT EXISTS / idempotent.

create table if not exists public.audit_log (
    id      bigint generated by default as identity primary key,
    log_id  text not null,
    user_id text not null,
    actor   text not null default '',
    action  text not null default '',
    detail  text not null default '',
    ref     text not null default '',
    at      timestamptz not null default now()
);

create unique index if not exists audit_log_logid_uniq on public.audit_log (log_id);
create index if not exists audit_log_user_at_idx on public.audit_log (user_id, at desc);

grant select, insert, update, delete on public.audit_log to anon, authenticated;

alter table public.audit_log enable row level security;

drop policy if exists tenant_rw on public.audit_log;
create policy tenant_rw on public.audit_log
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());
