-- Per-medicine reorder level (the "buy more when stock drops below this" number).
-- The Inventory "To Buy" tab shows a smart default from each medicine's sales speed;
-- this table stores only the MANUAL overrides the owner sets for specific items.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New query
-- -> paste -> Run). Safe to re-run — idempotent.

create table if not exists public.reorder_levels (
    id           bigint generated by default as identity primary key,
    user_id      text not null,
    product_name text not null,
    level        numeric not null default 0
);

create unique index if not exists reorder_levels_user_prod_uniq
    on public.reorder_levels (user_id, product_name);

grant select, insert, update, delete on public.reorder_levels to anon, authenticated;

alter table public.reorder_levels enable row level security;

drop policy if exists tenant_rw on public.reorder_levels;
create policy tenant_rw on public.reorder_levels
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());
