-- Shop running costs — rent, salaries, electricity, freight and the rest.
--
-- WHY: every "profit" figure in the app was (Sale - Purchase) x Qty, which is
-- gross margin. Nothing subtracted the cost of actually running the shop,
-- because there was nowhere to record it. With this table the Report page can
-- show a real net profit instead of relabelling margin as one.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New
-- query -> paste -> Run). Safe to re-run — idempotent.

create table if not exists public.expenses (
    id           bigint generated by default as identity primary key,
    expense_id   text not null,
    user_id      text not null,
    exp_date     date not null,
    category     text not null default 'Other',
    note         text default '',
    amount       numeric not null default 0,
    payment_mode text default 'Cash',
    saved_at     timestamptz default now()
);

-- expense_id is the app-generated string, so a re-sync updates the same row
-- instead of inserting a duplicate (same pattern as customer_payments).
create unique index if not exists expenses_eid_uniq
    on public.expenses (expense_id);

-- Reports filter by date within a shop, so index the pair.
create index if not exists expenses_user_date_idx
    on public.expenses (user_id, exp_date);

grant select, insert, update, delete on public.expenses to anon, authenticated;

alter table public.expenses enable row level security;

drop policy if exists tenant_rw on public.expenses;
create policy tenant_rw on public.expenses
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());

-- ── IMPORTANT ───────────────────────────────────────────────────────────────
-- Add 'expenses' to the tbls array in migrations/add_delete_store_cascade.sql
-- and re-run that file, or a deleted shop will leave its expense rows behind.
-- The updated array is applied by re-running that migration as-is once this
-- table exists; the trigger skips tables that are not present.
