-- A record that an account WAS reconciled, and to what.
--
-- Without this, reconciling is a thing you do and then cannot prove. The
-- question an accountant actually asks is "when was this account last agreed
-- with the bank, and did it agree?" — so that is what is stored: the period,
-- the statement's closing balance, the books' balance, and the difference
-- that remained.
--
-- DELIBERATELY NOT STORING EVERY STATEMENT LINE. A bank statement is the
-- bank's document, not the shop's; copying thousands of its rows into this
-- database would create a second, staler copy of something the shop can
-- re-download any time, and every one of those rows would then need its own
-- correctness story. What is worth keeping is the CONCLUSION.
--
-- difference = 0 means everything was explained. A non-zero difference is
-- kept rather than blocked: a shop may legitimately close a reconciliation
-- with a known, named gap it intends to chase, and hiding that is worse than
-- recording it.
--
-- Run this ONCE in the Supabase SQL editor. Safe to re-run.

create table if not exists public.bank_reconciliations (
    id                bigint generated by default as identity primary key,
    recon_id          text not null,
    user_id           text not null,
    account_id        text not null,
    from_date         date,
    to_date           date,
    statement_closing numeric not null default 0,
    book_balance      numeric not null default 0,
    difference        numeric not null default 0,
    matched_count     integer not null default 0,
    bank_only_count   integer not null default 0,
    book_only_count   integer not null default 0,
    note              text default '',
    saved_at          timestamptz not null default now()
);

-- Client-generated id, same idempotency pattern as customer_payments.
create unique index if not exists bank_reconciliations_rid_uniq
    on public.bank_reconciliations (recon_id);

create index if not exists bank_reconciliations_acct_idx
    on public.bank_reconciliations (user_id, account_id, to_date desc);

grant select, insert, update, delete on public.bank_reconciliations to anon, authenticated;

alter table public.bank_reconciliations enable row level security;

drop policy if exists tenant_rw on public.bank_reconciliations;
create policy tenant_rw on public.bank_reconciliations
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());

comment on table public.bank_reconciliations is
    'One row per completed bank reconciliation: the period, both closing balances and the unexplained difference. Statement LINES are deliberately not stored — the bank owns that document.';
