-- The shop's own list of Schedule X (narcotic / psychotropic) drug names.
-- Since X drugs are few and the shop knows exactly which products they stock,
-- the owner marks them once and the app then treats them as Schedule X everywhere
-- (X badge, H1/X filter, mandatory patient + doctor at sale). Mirrors schedule_h_drugs.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New query
-- -> paste -> Run). Safe to re-run — everything is IF NOT EXISTS / idempotent.

create table if not exists public.schedule_x_drugs (
    id      bigint generated by default as identity primary key,
    user_id text not null,
    name    text not null
);

create unique index if not exists schedule_x_drugs_user_name_uniq
    on public.schedule_x_drugs (user_id, name);

grant select, insert, update, delete on public.schedule_x_drugs to anon, authenticated;

alter table public.schedule_x_drugs enable row level security;

drop policy if exists tenant_rw on public.schedule_x_drugs;
create policy tenant_rw on public.schedule_x_drugs
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());
