-- System-wide announcements shown in every shop's Inbox (📢 Updates).
-- GLOBAL table (not per-tenant): one announcement is visible to all accounts.
-- Read-only from the browser; you post announcements yourself from the Supabase
-- SQL editor / Table editor (see the sample insert at the bottom).
--
-- Columns match js/notifications.js -> generateSystemAlerts():
--   title, message, icon, created_at.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New query
-- -> paste -> Run). Safe to re-run — everything is IF NOT EXISTS / idempotent.

create table if not exists public.mm_announcements (
    id           bigint generated by default as identity primary key,
    title        text not null default '',
    message      text not null default '',
    icon         text default '📢',
    created_at   timestamptz not null default now()
);

-- Everyone may READ announcements; nobody writes from the browser (you insert
-- them yourself in the dashboard), so no insert/update/delete grant is given.
grant select on public.mm_announcements to anon, authenticated;

alter table public.mm_announcements enable row level security;

drop policy if exists announcements_read on public.mm_announcements;
create policy announcements_read on public.mm_announcements
    for select
    using (true);

-- ── To post an announcement later, run something like: ──
-- insert into public.mm_announcements (title, message, icon)
-- values ('🎉 New feature', 'Barcode billing is now live on the Sales page.', '📢');
