-- Supplier master — the shop's list of suppliers/distributors with their details
-- (GSTIN, phone, address). Purchases pick the supplier from this list (so names
-- stay consistent), and the Supplier Ledger groups by it. Mirrors customers/doctors.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New query
-- -> paste -> Run). Safe to re-run — everything is IF NOT EXISTS / idempotent.

create table if not exists public.suppliers (
    id       bigint generated by default as identity primary key,
    user_id  text not null,
    name     text not null,
    gstin    text not null default '',
    phone    text not null default '',
    address  text not null default '',
    created_at timestamptz not null default now()
);

create unique index if not exists suppliers_user_name_uniq
    on public.suppliers (user_id, name);

grant select, insert, update, delete on public.suppliers to anon, authenticated;

alter table public.suppliers enable row level security;

drop policy if exists tenant_rw on public.suppliers;
create policy tenant_rw on public.suppliers
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());
