-- Supplier-payments ledger (accounts payable). Records money paid to a supplier
-- so the app can show what you still owe each supplier:
--   balance = purchases − purchase-returns (debit notes) − payments.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New query
-- -> paste -> Run). Safe to re-run — everything is IF NOT EXISTS / idempotent.

create table if not exists public.supplier_payments (
    id         bigint generated by default as identity primary key,
    payment_id text not null,
    user_id    text not null,
    firm       text not null default '',
    amount     numeric not null default 0,
    pay_date   date,
    note       text not null default '',
    saved_at   timestamptz not null default now()
);

create unique index if not exists supplier_payments_pid_uniq
    on public.supplier_payments (payment_id);

grant select, insert, update, delete on public.supplier_payments to anon, authenticated;

alter table public.supplier_payments enable row level security;

drop policy if exists tenant_rw on public.supplier_payments;
create policy tenant_rw on public.supplier_payments
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());
