-- Makes a khata balance change IDEMPOTENT and race-free.
--
-- THE BUG THIS FIXES
-- dbUpdateCustomerBalance() reads the balance, adds a delta, and writes the
-- result back. If that write COMMITS but the response is lost (patchy shop
-- wifi, tab closed, phone sleeps), the client cannot tell it from a failure:
-- it queues the delta in pendingBalanceUpdates and dbSyncPendingCustomerBalances
-- applies it a SECOND time. The customer is then billed twice for one credit
-- sale, or refunded twice for one return. Same "the write is not idempotent"
-- class as v300's triplicated credit notes.
--
-- Read-modify-write from the browser also loses updates outright: two devices
-- billing the same customer at once both read 100, both write 150, and one
-- ₹50 sale vanishes. PostgREST cannot express "balance = balance + x", which
-- is why the client was doing arithmetic in the first place — so the fix has
-- to live in the database.
--
-- WHAT THIS DOES
-- Every balance change carries an op_id generated ONCE by the client and
-- reused on every retry. The function below applies the delta and records the
-- op_id in the SAME transaction, so either both happen or neither does. A
-- retry of an op that already landed is recognised and does nothing.
--
-- Run this ONCE in the Supabase SQL editor (Dashboard -> SQL Editor -> New
-- query -> paste -> Run). Safe to re-run — idempotent.
--
-- Until it is run the app keeps working: the client falls back to the old
-- read-modify-write path (and logs that it did), so nothing breaks, the
-- double-count risk simply remains.

create table if not exists public.customer_balance_ops (
    id          bigint generated by default as identity primary key,
    op_id       text not null,
    user_id     text not null,
    customer_id bigint,
    name        text default '',
    delta       numeric not null default 0,
    applied_at  timestamptz default now()
);

-- The whole point: the second attempt at the same op cannot insert.
create unique index if not exists customer_balance_ops_opid_uniq
    on public.customer_balance_ops (op_id);

create index if not exists customer_balance_ops_user_idx
    on public.customer_balance_ops (user_id, applied_at desc);

grant select, insert, update, delete on public.customer_balance_ops to anon, authenticated;

alter table public.customer_balance_ops enable row level security;

drop policy if exists tenant_rw on public.customer_balance_ops;
create policy tenant_rw on public.customer_balance_ops
    for all
    using (user_id = public.current_tenant())
    with check (user_id = public.current_tenant());


-- One statement from the client = one transaction, so the balance move and the
-- op_id record commit together or not at all.
--
-- security invoker, deliberately: the caller's RLS still applies to every row
-- this touches, so the function cannot be used to reach another shop's
-- customers even if it were called with a forged name.
create or replace function public.mm_apply_balance_delta(
    p_op_id   text,
    p_name    text,
    p_phone   text,
    p_address text,
    p_delta   numeric
) returns jsonb
language plpgsql
security invoker
as $$
declare
    v_user text := public.current_tenant();
    v_row  public.customers%rowtype;
    v_new  numeric;
begin
    if v_user is null or btrim(coalesce(p_op_id, '')) = '' then
        raise exception 'mm_apply_balance_delta: no tenant or no op_id';
    end if;

    -- Already applied. This is a retry of a write that DID land — report the
    -- balance as it stands and change nothing.
    if exists (select 1 from public.customer_balance_ops where op_id = p_op_id) then
        select * into v_row from public.customers
         where user_id = v_user
           and lower(btrim(name)) = lower(btrim(p_name))
         order by id limit 1;
        return jsonb_build_object('applied', false, 'duplicate', true,
                                  'balance', coalesce(v_row.balance, 0));
    end if;

    -- Matched case-insensitively on purpose: every local match in the app
    -- lowercases, and a case-sensitive lookup here is what used to create a
    -- second customer row for the same person.
    -- FOR UPDATE serialises two devices billing the same customer at once.
    select * into v_row from public.customers
     where user_id = v_user
       and lower(btrim(name)) = lower(btrim(p_name))
     order by id limit 1
       for update;

    if found then
        -- Clamped at zero to match every reader: dbGetKhataData filters
        -- balance > 0 and the local stores have always clamped.
        v_new := greatest(0, coalesce(v_row.balance, 0) + p_delta);
        update public.customers set balance = v_new where id = v_row.id;
    else
        v_new := greatest(0, p_delta);
        insert into public.customers (name, phone, address, balance, user_id)
        values (btrim(p_name), coalesce(p_phone, ''), coalesce(p_address, ''), v_new, v_user)
        returning * into v_row;
    end if;

    insert into public.customer_balance_ops (op_id, user_id, customer_id, name, delta)
    values (p_op_id, v_user, v_row.id, btrim(p_name), p_delta);

    return jsonb_build_object('applied', true, 'duplicate', false, 'balance', v_new);
end
$$;

grant execute on function public.mm_apply_balance_delta(text, text, text, text, numeric)
    to anon, authenticated;
